apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1,djangotest.com,django-ecommerce-production-81b6.up.railway.app"
  CSRF_TRUSTED_ORIGINS: "https://djangotest.com,https://django-ecommerce-production-81b6.up.railway.app"
