apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  SECRET_KEY: eWR0a2tmaXVrZ2Zkd3R1eWl0dWdkc3M=  # Base64 encoded secret
  DB_NAME: ZGpqYW5nZV9FY29tbWVyY2U=           # Base64 encoded DB name
  DB_USER: cG9zdGdyZXM=                     # Base64 encoded DB user
  DB_PASSWORD: MjA5MDg1MDM=                 # Base64 encoded DB password
  PAYPAL_RECEIVER_EMAIL: YnVzaW5lc3NAY29kZW15dGVzdC5jb20=  # Base64 encoded PayPal email
