---
- name: Setup PostgreSQL on Kubernetes
  hosts: localhost
  become: false
  vars_files:
    - /mnt/c/Users/Lenovo/Desktop/devops/Django_Ecommerce/ansible/vars.yml
  tasks:
    - name: Deploy PostgreSQL as a Kubernetes deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: postgres-db
            namespace: "{{ kubernetes_namespace }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: postgres-db
            template:
              metadata:
                labels:
                  app: postgres-db
              spec:
                containers:
                  - name: postgres
                    image: postgres:latest
                    env:
                      - name: POSTGRES_PASSWORD
                        value: "{{ postgres_password }}"
                      - name: POSTGRES_USER
                        value: "{{ postgres_user }}"
                      - name: POSTGRES_DB
                        value: "{{ postgres_db }}"
                    ports:
                      - containerPort: 5432

    - name: Expose PostgreSQL as a service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: postgres-db
            namespace: "{{ kubernetes_namespace }}"
          spec:
            selector:
              app: postgres-db
            ports:
              - port: 5432
                targetPort: 5432
            type: ClusterIP